name: relaya
region: nyc
services:
- name: web
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
  build_command: npm run build
  run_command: npm start
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
