import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ScrollToTop from '@/components/ScrollToTop';

const Disclaimer = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <ScrollToTop />
      <Header />
      <main className="flex-1 bg-background">
        <div className="container max-w-4xl py-12 md:py-16">
          <h1 className="text-4xl font-bold mb-8">Disclaimer</h1>
          <div className="prose prose-slate dark:prose-invert max-w-none">
            <p className="text-muted-foreground mb-6">
              <strong>Last Updated:</strong> January 24, 2026
            </p>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">1. General Information</h2>
              <p className="text-muted-foreground">
                The information provided by Relaya ("we," "us," or "our") on our website and through our services is for general informational purposes only. All information is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">2. AI-Generated Content</h2>
              <p className="text-muted-foreground mb-4">
                Our platform uses artificial intelligence to generate public relations and marketing content. You acknowledge and agree that:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>AI-generated content is produced by machine learning algorithms and may contain errors, inaccuracies, or biases</li>
                <li>All AI-generated content should be reviewed, fact-checked, and edited by qualified humans before publication or distribution</li>
                <li>We do not guarantee the accuracy, appropriateness, or legal compliance of AI-generated content</li>
                <li>You are solely responsible for verifying and approving all content before use</li>
                <li>AI-generated content may not be suitable for all purposes and should be evaluated based on your specific needs</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">3. Professional Advice</h2>
              <p className="text-muted-foreground mb-4">
                The content generated by our platform does not constitute professional advice. You should not rely on our services as a substitute for:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Legal advice from a qualified attorney</li>
                <li>Professional public relations counsel</li>
                <li>Marketing strategy consultation</li>
                <li>Business advice from qualified consultants</li>
                <li>Technical or specialized expertise in your industry</li>
              </ul>
              <p className="text-muted-foreground mt-4">
                Always consult with appropriate professionals before making important business decisions based on AI-generated content.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">4. No Warranty</h2>
              <p className="text-muted-foreground">
                Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of our services or reliance on any information provided. Your use of our services and reliance on any information is solely at your own risk.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">5. External Links</h2>
              <p className="text-muted-foreground">
                Our services may contain links to external websites or resources that are not provided or maintained by us. We do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites. The inclusion of any link does not imply endorsement, approval, or control of the linked website.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">6. Service Availability</h2>
              <p className="text-muted-foreground mb-4">
                We do not warrant that:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Our services will be available at all times or without interruption</li>
                <li>Our services will be error-free or free from viruses or other harmful components</li>
                <li>The results obtained from our services will be accurate or reliable</li>
                <li>Any defects in our services will be corrected</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">7. User Responsibility</h2>
              <p className="text-muted-foreground mb-4">
                You are responsible for:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Ensuring all content you publish meets applicable laws and regulations</li>
                <li>Obtaining necessary permissions, licenses, and rights for content use</li>
                <li>Fact-checking and verifying all AI-generated information</li>
                <li>Compliance with industry standards and professional ethics</li>
                <li>Protecting your account credentials and maintaining account security</li>
                <li>Backing up your content and data</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">8. Intellectual Property</h2>
              <p className="text-muted-foreground">
                While we provide tools to generate content, you are responsible for ensuring that all content you publish does not infringe upon the intellectual property rights of others. We are not responsible for any copyright, trademark, or other intellectual property violations arising from your use of our services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">9. Compliance and Legal Requirements</h2>
              <p className="text-muted-foreground">
                You are responsible for ensuring compliance with all applicable laws, regulations, and industry standards in your jurisdiction. This includes but is not limited to advertising regulations, truth-in-advertising laws, data protection regulations, and industry-specific guidelines.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">10. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                To the fullest extent permitted by law, in no event will Relaya, its affiliates, directors, officers, employees, or agents be liable to you or any third party for any direct, indirect, consequential, exemplary, incidental, special, or punitive damages, including lost profit, lost revenue, loss of data, or other damages arising from your use of our services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">11. Testimonials and Case Studies</h2>
              <p className="text-muted-foreground">
                Any testimonials, case studies, or examples of results displayed on our website represent individual experiences and results may vary. We do not guarantee that you will achieve similar results.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">12. Updates to Services</h2>
              <p className="text-muted-foreground">
                We reserve the right to modify, suspend, or discontinue our services (or any part thereof) at any time without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuance of our services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">13. Indemnification</h2>
              <p className="text-muted-foreground">
                You agree to indemnify and hold harmless Relaya and its affiliates from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from your use of our services, violation of these terms, or infringement of any third-party rights.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">14. Changes to This Disclaimer</h2>
              <p className="text-muted-foreground">
                We reserve the right to modify this disclaimer at any time. Changes will be effective immediately upon posting to our website. Your continued use of our services after changes constitutes acceptance of the updated disclaimer.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">15. Contact Information</h2>
              <p className="text-muted-foreground">
                If you have any questions about this disclaimer, please contact us at:
              </p>
              <div className="mt-4 text-muted-foreground">
                <p>Email: legal@relaya.com</p>
                <p>Address: [Your Business Address]</p>
              </div>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Disclaimer;
