import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ScrollToTop from '@/components/ScrollToTop';

const TermsOfService = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <ScrollToTop />
      <Header />
      <main className="flex-1 bg-background">
        <div className="container max-w-4xl py-12 md:py-16">
          <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
          <div className="prose prose-slate dark:prose-invert max-w-none">
            <p className="text-muted-foreground mb-6">
              <strong>Last Updated:</strong> January 24, 2026
            </p>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">1. Agreement to Terms</h2>
              <p className="text-muted-foreground">
                By accessing or using Relaya's services, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using our services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
              <p className="text-muted-foreground mb-4">
                Relaya provides an AI-powered platform for generating public relations and marketing content. Our services include:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>AI-generated PR content (press releases, articles, social media posts)</li>
                <li>Brand voice training and content optimization</li>
                <li>Campaign planning and management tools</li>
                <li>SEO analysis and competitor research</li>
                <li>Image generation and editing capabilities</li>
                <li>Social media publishing and scheduling</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">3. User Accounts</h2>
              <h3 className="text-xl font-semibold mb-3">3.1 Account Creation</h3>
              <p className="text-muted-foreground mb-4">
                You must create an account to use our services. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate.
              </p>

              <h3 className="text-xl font-semibold mb-3">3.2 Account Security</h3>
              <p className="text-muted-foreground mb-4">
                You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. Notify us immediately of any unauthorized use.
              </p>

              <h3 className="text-xl font-semibold mb-3">3.3 Account Termination</h3>
              <p className="text-muted-foreground">
                We reserve the right to suspend or terminate your account for violations of these Terms or for any reason at our discretion.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">4. Acceptable Use</h2>
              <p className="text-muted-foreground mb-4">You agree not to:</p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>Use our services for any illegal or unauthorized purpose</li>
                <li>Generate content that violates intellectual property rights</li>
                <li>Create misleading, defamatory, or harmful content</li>
                <li>Attempt to gain unauthorized access to our systems</li>
                <li>Interfere with or disrupt our services or servers</li>
                <li>Use automated tools to access our services without permission</li>
                <li>Resell or redistribute our services without authorization</li>
                <li>Generate spam, malware, or other malicious content</li>
                <li>Impersonate another person or entity</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">5. Content Ownership and License</h2>
              <h3 className="text-xl font-semibold mb-3">5.1 Your Content</h3>
              <p className="text-muted-foreground mb-4">
                You retain ownership of content you upload to our platform. By uploading content, you grant us a worldwide, non-exclusive, royalty-free license to use, process, and display your content solely to provide our services.
              </p>

              <h3 className="text-xl font-semibold mb-3">5.2 Generated Content</h3>
              <p className="text-muted-foreground mb-4">
                Content generated by our AI tools is provided to you for your use. You are responsible for reviewing and verifying all generated content before publication or distribution. We do not claim ownership of AI-generated content created for you.
              </p>

              <h3 className="text-xl font-semibold mb-3">5.3 Our Platform</h3>
              <p className="text-muted-foreground">
                All rights, title, and interest in our platform, including software, algorithms, and documentation, remain our exclusive property.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">6. Payment and Subscriptions</h2>
              <h3 className="text-xl font-semibold mb-3">6.1 Pricing</h3>
              <p className="text-muted-foreground mb-4">
                Pricing for our services is available on our website. We reserve the right to modify pricing with reasonable notice to existing subscribers.
              </p>

              <h3 className="text-xl font-semibold mb-3">6.2 Billing</h3>
              <p className="text-muted-foreground mb-4">
                Subscription fees are billed in advance on a recurring basis. You authorize us to charge your payment method for all fees incurred.
              </p>

              <h3 className="text-xl font-semibold mb-3">6.3 Refunds</h3>
              <p className="text-muted-foreground mb-4">
                Refund requests are evaluated on a case-by-case basis. Generally, fees are non-refundable except as required by law.
              </p>

              <h3 className="text-xl font-semibold mb-3">6.4 Cancellation</h3>
              <p className="text-muted-foreground">
                You may cancel your subscription at any time. Cancellations take effect at the end of the current billing period.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">7. Disclaimers and Limitations</h2>
              <h3 className="text-xl font-semibold mb-3">7.1 Service Availability</h3>
              <p className="text-muted-foreground mb-4">
                We strive to maintain service availability but do not guarantee uninterrupted access. Services may be temporarily unavailable for maintenance or technical reasons.
              </p>

              <h3 className="text-xl font-semibold mb-3">7.2 Content Accuracy</h3>
              <p className="text-muted-foreground mb-4">
                AI-generated content is provided as-is. You are responsible for reviewing, fact-checking, and verifying all content before use. We do not guarantee the accuracy, completeness, or suitability of generated content.
              </p>

              <h3 className="text-xl font-semibold mb-3">7.3 No Warranties</h3>
              <p className="text-muted-foreground">
                Our services are provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">8. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                To the maximum extent permitted by law, Relaya shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of our services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">9. Indemnification</h2>
              <p className="text-muted-foreground">
                You agree to indemnify and hold harmless Relaya and its affiliates from any claims, damages, losses, liabilities, and expenses arising from your use of our services, violation of these Terms, or infringement of any third-party rights.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">10. Intellectual Property</h2>
              <p className="text-muted-foreground mb-4">
                All intellectual property rights in our platform, including trademarks, service marks, logos, and trade names, are owned by or licensed to Relaya. You may not use our intellectual property without prior written consent.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">11. Privacy</h2>
              <p className="text-muted-foreground">
                Your use of our services is also governed by our Privacy Policy, which is incorporated into these Terms by reference.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">12. Modifications to Terms</h2>
              <p className="text-muted-foreground">
                We reserve the right to modify these Terms at any time. Material changes will be communicated via email or through our platform. Continued use of our services after changes constitutes acceptance of the modified Terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">13. Governing Law</h2>
              <p className="text-muted-foreground">
                These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law provisions.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">14. Dispute Resolution</h2>
              <p className="text-muted-foreground">
                Any disputes arising from these Terms or our services shall be resolved through binding arbitration in accordance with the rules of [Arbitration Organization], except where prohibited by law.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">15. Severability</h2>
              <p className="text-muted-foreground">
                If any provision of these Terms is found to be unenforceable, the remaining provisions shall remain in full force and effect.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">16. Contact Information</h2>
              <p className="text-muted-foreground">
                For questions about these Terms, contact us at:
              </p>
              <div className="mt-4 text-muted-foreground">
                <p>Email: legal@relaya.com</p>
                <p>Address: [Your Business Address]</p>
              </div>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default TermsOfService;
